# Generated by Django 4.1.3 on 2022-12-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_userregister_dob_alter_userregister_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregister',
            options={},
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='username',
        ),
    ]
